// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScaffoldDB.Context;

#nullable disable

namespace ScaffoldDB.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScaffoldDB.Migrations.Client", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("RowVersion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Email");

                    b.HasIndex(new[] { "Email" }, "IX_Clients_Email");

                    b.HasIndex(new[] { "FirstName" }, "IX_Clients_FirstName");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.ClientRentalStatistic", b =>
                {
                    b.Property<decimal?>("AverageRentalDuration")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("TotalRents")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("ClientRentalStatistics", (string)null);
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.DamageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RepairCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RentId" }, "IX_DamageReports_RentId");

                    b.ToTable("DamageReports");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.InsurancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("VehicleLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VehicleLicensePlate" }, "IX_InsurancePolicies_VehicleLicensePlate");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PayTerm")
                        .HasColumnType("date");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RentId" }, "IX_Invoices_RentId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Office", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Name");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Rating1")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Proccessed'::character varying");

                    b.Property<string>("VehicleLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "ClientEmail" }, "IX_Rents_ClientEmail");

                    b.HasIndex(new[] { "ClientEmail", "VehicleLicensePlate" }, "IX_Rents_ClientEmail_VehicleLicensePlate");

                    b.HasIndex(new[] { "Cost" }, "IX_Rents_Cost");

                    b.HasIndex(new[] { "VehicleLicensePlate" }, "IX_Rents_VehicleLicensePlate");

                    b.HasIndex(new[] { "WorkerId" }, "IX_Rents_WorkerId");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.RentStatus", b =>
                {
                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Status");

                    b.ToTable("RentStatuses");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RatingId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("VehicleLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.HasIndex(new[] { "ClientEmail" }, "IX_Reviews_ClientEmail");

                    b.HasIndex(new[] { "VehicleLicensePlate" }, "IX_Reviews_VehicleLicensePlate");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.ServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ServiceCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("VehicleLicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ServiceDate" }, "IX_ServiceRecords_ServiceDate");

                    b.HasIndex(new[] { "VehicleLicensePlate" }, "IX_ServiceRecords_VehicleLicencePlate");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Vehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CostPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LicensePlate");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_Vehicles_LicensePlate");

                    b.HasIndex(new[] { "OfficeName" }, "IX_Vehicles_OfficeName");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OccupationalPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OfficeName" }, "IX_Workers_OfficeName");

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Workers_PhoneNumber_HASH");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "PhoneNumber" }, "IX_Workers_PhoneNumber_HASH"), "hash");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.DamageReport", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Rent", "Rent")
                        .WithMany("DamageReports")
                        .HasForeignKey("RentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.InsurancePolicy", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Vehicle", "VehicleLicensePlateNavigation")
                        .WithMany("InsurancePolicies")
                        .HasForeignKey("VehicleLicensePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleLicensePlateNavigation");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Invoice", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Rent", "Rent")
                        .WithOne("Invoice")
                        .HasForeignKey("ScaffoldDB.Migrations.Invoice", "RentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_rents_rentid");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Rent", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Client", "ClientEmailNavigation")
                        .WithMany("Rents")
                        .HasForeignKey("ClientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rents_clients_clientemail");

                    b.HasOne("ScaffoldDB.Migrations.RentStatus", "StatusNavigation")
                        .WithMany("Rents")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("fk_rents_status");

                    b.HasOne("ScaffoldDB.Migrations.Vehicle", "VehicleLicensePlateNavigation")
                        .WithMany("Rents")
                        .HasForeignKey("VehicleLicensePlate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScaffoldDB.Migrations.Worker", "Worker")
                        .WithMany("Rents")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rents_workers_workerid");

                    b.Navigation("ClientEmailNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("VehicleLicensePlateNavigation");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Review", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Client", "ClientEmailNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScaffoldDB.Migrations.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .HasConstraintName("fk_reviews_ratings_ratingid");

                    b.HasOne("ScaffoldDB.Migrations.Vehicle", "VehicleLicensePlateNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("VehicleLicensePlate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientEmailNavigation");

                    b.Navigation("Rating");

                    b.Navigation("VehicleLicensePlateNavigation");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.ServiceRecord", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Vehicle", "VehicleLicensePlateNavigation")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleLicensePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceRecords_Vehicles_VehicleLicencePlate");

                    b.Navigation("VehicleLicensePlateNavigation");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Vehicle", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Office", "OfficeNameNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("OfficeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_offices_officename");

                    b.Navigation("OfficeNameNavigation");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Worker", b =>
                {
                    b.HasOne("ScaffoldDB.Migrations.Office", "OfficeNameNavigation")
                        .WithMany("Workers")
                        .HasForeignKey("OfficeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workers_offices_officename");

                    b.Navigation("OfficeNameNavigation");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Client", b =>
                {
                    b.Navigation("Rents");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Office", b =>
                {
                    b.Navigation("Vehicles");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Rating", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Rent", b =>
                {
                    b.Navigation("DamageReports");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.RentStatus", b =>
                {
                    b.Navigation("Rents");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Vehicle", b =>
                {
                    b.Navigation("InsurancePolicies");

                    b.Navigation("Rents");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("ScaffoldDB.Migrations.Worker", b =>
                {
                    b.Navigation("Rents");
                });
#pragma warning restore 612, 618
        }
    }
}
